services:
 
    db:
        image: mysql:8.0.40
        container_name: coin-admin-db
        expose:
            - 3306
        ports:
            - "3306:3306"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - /www/apps/docker-data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: infromation@admin
            MYSQL_DATABASE: bob
            MYSQL_USER: bobroot
            MYSQL_PASSWORD: infromation@admin@bobroot
        networks:
            - common-network

 
    coin-admin:
        build: 
            context: ./
            dockerfile: ./Dockerfile
        # image: /home/backend/coin-admin
        restart: always
        depends_on:
            - db
        ports:
            - "3000:3000"
        networks:
            - common-network

networks:
    common-network:
        driver: bridge